### ISSUE TITLE
Issue with `expand-exprs`

### ISSUE THREAD

**Issue by shaunsingh** [datwaft/themis.nvim#4]
Hi, trying to work on a macro and running into an issue

```lisp
(macro repro [...]
  (var moduletag nil)
  (fn testprint [name]
    (if (= :string (type name))
      (set moduletag name))
    (if (sym? name)
      (let [name (.. moduletag (tostring name))]
        `(print ,name))))
  (fn exprs [...]
    (match [...]
      (where [& rest]  (= 0 (length rest))) []
      [name & rest] [(testprint name)
                     (unpack (exprs (unpack rest)))]
      _ []))
  (let [exprs (exprs ...)]
    (expand-exprs exprs)))

(macrodebug (repro :test name1 name2 :test2 name1 name2))
```

results in 
```
; (out) (do nil (print "testname1") (print "testname2"))
```

though I believe it should result in 
```
; (out) (do nil (print "testname1") (print "testname2") (print "test2name1") (print "test2name2"))
```

**Comment by bangedorrunt** [comment]
@shaunsingh move `moduletag`, `testprint` and `exprs` inside `let` body to see the result. I had the issue with define function out side `let` body as same as you. Hopefully it's not related to `expand-exprs` macro :)

**Comment by datwaft** [comment]
I added an small print statement. It seems the problem is in your `exprs` statement, it is probably not iterating properly.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/191791377-11d69b7a-bc4b-4c73-b7d0-36e133f7ad23.png">

**Comment by datwaft** [comment]
Why don't you use the iterative approach instead of the recursive one?

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/191792537-545dbbf7-bb3c-4eff-abb6-3f241315bc97.png">

As you can see it works when using `icollect`.

Here is the code snippet:

```fennel
(fn repro2 [...]
  (var moduletag nil)
  (fn testprint [name]
    (if (= :string (type name))
      (set moduletag name))
    (if (sym? name)
      (let [name (.. moduletag (tostring name))]
        `(print ,name))))
  (expand-exprs (icollect [_ name (ipairs [...])]
                  (testprint name))))
```

**Edit:** here is the output with a better format:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/191794149-13c7adc4-8c67-4ce4-a130-087a0e65b0f3.png">

**Comment by datwaft** [comment]
Testing it a little more, it seems that the problem is that `nil` is present in the middle of the `exprs` list, which means that `length` and `unpack` doesn't work as expected.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/191796375-a82b0c33-9a0b-4322-83d1-c0193ca82d41.png">

To find this I made `repro` add `:test` instead of `nil` to the list.

**Comment by datwaft** [comment]
I will close this issue because if inactivity.
